database.url=jdbc:postgresql://127.0.0.1:5432/postgres
database.username=postgres
database.password=123
database.driver=org.postgresql.Driver

schedule.timeout=5
thread.poolSize=100
process.fileFetching.count=1
process.fileScanning.count=7
process.fileGrouping.count=3
process.fileLinking.count=1

spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Samara

logging.level.org.jproject=DEBUG
logging.file.name=logs/myapp.log
logging.logback.rollingpolicy.max-file-size=200MB

handlers = logging.FileHandler
logging.FileHandler.pattern = myapp.log
logging.FileHandler.limit = 50000
logging.FileHandler.count = 1
logging.FileHandler.formatter = java.util.logging.SimpleFormatter
