hibernate.show_sql = true
hbm2ddl.auto = validate
hibernate.format_sql = true

hibernate.type = trace
hibernate.hikari.maximumPoolSize = 2000
hibernate.connection.pool_size = 2000
hibernate.c3p0.max_size = 2000
